### ISSUE TITLE
New spyctl get features

### ISSUE THREAD

**Issue by brent-spyder** [spyderbat/spyctl#44]
- [x] Get redflags
- [x] Get opsflags
- [x] Get nodes (k8s)
- [x] Get processes
- [x] Get connections
- [x] Get deployments (k8s)
- [ ] Get connection-bundles
- [x] Get spydertraces
- [x] Get containers

**Comment by bsmith1180** [comment]
A couple of additions:

- [ ] connection bundles
- [ ] spydertraces

**Comment by brent-spyder** [comment]
- [ ] containers

**Comment by brent-spyder** [comment]
Fields in Spydertrace tabular summary:

ROOT_PROCESS, TRIGGER_NAME, UNIQUE_FLAGS, OBJECTS, START_TIME

For the -o wide tabular output

ROOT_PROCESS, TRIGGER_NAME, UNIQUE_FLAGS, PROCESSES, CONNECTIONS, DEPTH, SYSTEMS, OBJECTS, START_TIME

**Comment by brent-spyder** [comment]
done
